ALTER TABLE ai_assistant_logs
    ADD COLUMN rating TINYINT DEFAULT NULL,
    ADD COLUMN feedback TEXT DEFAULT NULL,
    ADD COLUMN category VARCHAR(50) DEFAULT NULL,
    ADD COLUMN sources JSON DEFAULT NULL,
    ADD COLUMN accepted TINYINT(1) DEFAULT NULL,
    ADD COLUMN corrected_after TINYINT(1) DEFAULT NULL,
    ADD COLUMN corrected_accounts JSON DEFAULT NULL,
    ADD COLUMN suggested_accounts JSON DEFAULT NULL,
    ADD COLUMN updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP;
